# I can quickly automatize the test with selenium ide
# it is not using POM model but can be done very fast
# there is an alert on the page when adding book,
# ide can not click ok button automaticly
# so i only rewrite that step

# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support import expected_conditions as EC

class TestLoginAddBook():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_loginAddBook(self):
    self.driver.get("https://demoqa.com/")
    self.driver.set_window_size(1920, 1080)
    self.driver.find_element(By.CSS_SELECTOR, ".card:nth-child(6) .card-up").click()
    self.driver.execute_script("window.scrollTo(0,103)")
    self.driver.find_element(By.ID, "login").click()
    self.driver.find_element(By.ID, "userName").click()
    self.driver.find_element(By.ID, "userName").send_keys("MelDem")
    self.driver.find_element(By.ID, "password").send_keys("Mel123,@Dem")
    self.driver.find_element(By.ID, "password").send_keys(Keys.ENTER)
    time.sleep(2)
    self.driver.find_element(By.LINK_TEXT, "Git Pocket Guide").click()
    self.driver.find_element(By.CSS_SELECTOR, ".text-right > #addNewRecordButton").click()
    WebDriverWait(self.driver, 10).until(EC.alert_is_present())
    self.driver.switch_to.alert.accept()
    self.driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
    self.driver.find_element(By.CSS_SELECTOR, ".show #item-3 > .text").click()
    self.driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
    time.sleep(2)
    self.driver.find_element(By.LINK_TEXT, "Git Pocket Guide").click()
    self.driver.find_element(By.ID, "addNewRecordButton").click()
    self.driver.find_element(By.ID, "submit").click()
  
